# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "SoBigData Master Projects"
subtitle: "LBDAI - SoBigData Master course results"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Projects developed by the students of the SoBigData Master's course LBDAI at the University of Pisa.


# Riportare il github del gruppo di progetto e quello del sito web (se differente).
# Tali informazioni appariranno nel Footer del sito.
github_repo:
  - name: "SoBigData LBDAI projects"
    url: "https://github.com/danielefadda/sobigdata-master-projects"

navbar:
  style :  dual #non modificare
  brand: # è il titolo del sito e funziona da bottone (tipicamente per la homepage).
    title :  "LBDAI - SoBigData Master Projects"
    img: "./assets/images/Logo_masthead.png"
    url: /
  nav:
    - title: 2024
      url: /2024.html
    - title: Search
      url: /search.html
    - title: Master website
      url: https://masterbigdata.it/




googlefonts:
  - url: "https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap"

chulapa-skin:
  skin:  "graymor" #"graymor" "gitdev-dark" "gitdev" "universal" "academia" "gitdev" "towards" "pear" "twitter-lights-out" "twitter-dim" "wandoo" "lymcha" "twitter" "chulapa" "sunset" "sunset" "minty" "lux" "journal" "deeply"
  vars:
    body-color: "#07286E"
    body-bg: "#fff"
    footer-chulapa-bg-color: "#07286E"
    footer-chulapa-text-color: "#fff"
    navbar-chulapa-bg-color: "#07286E"
    navbar-chulapa-text-color: "#fff"
    primary: "#07286E"
    # font-family-base: "Comic Neue"
    headings-font-family: "Rajdhani"



##################################################
#    NON modificare la sezione sottostante
##################################################

# Build settings
remote_theme: dieghernan/chulapa
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

collections:
  pages:
    output: true
    permalink: /:path

footer:
  links:
  - label: "LinkedIn"
    icon: "fab fa-linkedin"
    url: https://www.linkedin.com/company/sobigdata
  - label: "Twitter"
    icon: "fab fa-twitter"
    url: https://www.twitter.com/sobigdata
  - label: "Facebook"
    icon: "fab fa-facebook"
    url: https://www.facebook.com/sobigdata
  copyright: "2024 SoBigData Master Projects"


sass:
  quiet_deps: true

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Gemfile
 - Gemfile.lock
 - node_modules/
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - .idea/

livereload: true

baseurl: "/sobigdata-master-projects" # the subpath of your site, e.g. /blog
url: "https://danielefadda.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
#github_username:  jekyll

future: true
